name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'autoprepml/**'
      - 'tests/**'
      - 'setup.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'autoprepml/**'
      - 'tests/**'
      - 'setup.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Cache ruff
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-ruff-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-ruff-
    
    - name: Install ruff
      run: pip install ruff
    
    - name: Lint with ruff
      run: ruff check autoprepml/
      continue-on-error: true

  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        # Optimized: Only Ubuntu for most versions, other OS for critical version only
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']
        include:
          # Test Python 3.11 on all OS (most stable + common)
          - os: windows-latest
            python-version: '3.11'
          - os: macos-latest
            python-version: '3.11'
          # Python 3.13 is experimental - Ubuntu only
          - os: ubuntu-latest
            python-version: '3.13'
            experimental: true
    continue-on-error: ${{ matrix.experimental == true }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'setup.py'
        allow-prereleases: true
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/share/virtualenvs
        key: ${{ runner.os }}-py${{ matrix.python-version }}-deps-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-deps-
          ${{ runner.os }}-py${{ matrix.python-version }}-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,viz,llm]"
    
    - name: Run tests with pytest
      id: run_tests
      run: |
        pytest tests/ -v --cov=autoprepml --cov-report=xml --cov-report=term --maxfail=1 --tb=short 2>&1 | tee pytest.log
      continue-on-error: ${{ matrix.experimental == true }}
    
    - name: Upload test logs if failed
      if: failure() && steps.run_tests.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: failed-test-logs-${{ matrix.os }}-py${{ matrix.python-version }}-${{ github.run_id }}
        path: |
          pytest.log
          .pytest_cache/
        retention-days: 7
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
      continue-on-error: true

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Cache build tools
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-build-
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Check package
      run: twine check dist/*
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist/
        retention-days: 7
